LIKE 문법
https://lcs1245.tistory.com/entry/SQL-LIKE-%EC%97%B0%EC%82%B0%EC%9E%90-%EB%AC%B8%EC%9E%90%EC%97%B4-%EB%B6%80%EB%B6%84%EC%9D%BC%EC%B9%98-%EA%B2%80%EC%83%89

SELECT *
FROM 테이블
WHERE 칼럼 LIKE '쓰고싶은 문장'


JOIN 문법
https://yoo-hyeok.tistory.com/98


https://school.programmers.co.kr/learn/courses/30/lessons/131120
-- 코드를 입력하세요
SELECT P.MEMBER_ID, P.MEMBER_NAME, P.GENDER, DATE_FORMAT(P.DATE_OF_BIRTH,'%Y-%m-%d') AS DATA_OF_BIRTH
FROM MEMBER_PROFILE AS P
WHERE P.DATE_OF_BIRTH LIKE '%-03-%' AND P.GENDER LIKE 'W' AND P.TLNO IS NOT NULL
ORDER BY P.MEMBER_ID ASC
